import sqlite3

# Hàm để tạo bảng và thêm dữ liệu cố định
def setup_branch_users_table():
    # Kết nối tới cơ sở dữ liệu
    conn = sqlite3.connect('/home/trungdt2/Thuchanh/website-datloa/database/orders.db')
    cursor = conn.cursor()

    # Tạo bảng branch_users
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS branch_users (
            branch_code INTEGER PRIMARY KEY,
            branch_name TEXT NOT NULL
        )
    ''')

    # Dữ liệu cố định
    branch_users = [
        (246, 'Vĩnh Phúc'),
        (262, 'Bình Xuyên'),
        (182, 'Lai Châu'),
        (184, 'Điện Biên'),
        (282, 'Bắc Ninh'),
        (200, 'Lạng Sơn'),
        (170, 'Yên Bái'),
        (248, 'Bắc Phú Thọ'),
        (220, 'Thái Nguyên'),
        (242, 'Hùng Vương'),
        (280, 'Bắc Giang'),
        (244, 'TX Phú Thọ'),
        (174, 'Tuyên Quang'),
        (289, 'KCN Quế Võ'),
        (240, 'Phú Thọ'),
        (260, 'Phúc Yên'),
        (250, 'Hòa Bình'),
        (190, 'Sơn La'),
        (195, 'Hà Giang'),
        (285, 'KCN Tiên Sơn'),
        (284, 'Tiên Sơn'),
        (224, 'Lưu Xá'),
        (222, 'Nam Thái Nguyên'),
        (172, 'Bắc Kạn'),
        (180, 'Lào Cai'),
        (186, 'Cao Bằng'),
        (342, 'Hưng Yên'),
        (340, 'Hải Dương'),
        (169, 'Kiến An'),
        (304, 'Uông Bí'),
        (160, 'Hải Phòng'),
        (164, 'Lê Chân'),
        (344, 'Đông Hải Dương'),
        (162, 'Đông Hải Phòng'),
        (168, 'Ngô Quyền'),
        (166, 'Hồng Bàng'),
        (343, 'Bắc Hưng Yên'),
        (346, 'KCN Hải Dương'),
        (302, 'Cẩm Phả'),
        (316, 'Vân Đồn'),
        (306, 'Tây Quảng Ninh'),
        (161, 'Bắc Hải Phòng'),
        (300, 'Quảng Ninh'),
        (308, 'Móng Cái'),
        (320, 'Thành An'),
        (106, 'Chi nhánh TPHN'),
        (264, 'Quang Minh'),
        (122, 'Hoàn Kiếm'),
        (124, 'Ba Đình'),
        (328, 'Tây Thăng Long'),
        (126, 'Đống Đa'),
        (127, 'Thanh Xuân'),
        (128, 'Chương Dương'),
        (129, 'Bắc Hà Nội'),
        (131, 'Đông Hà Nội'),
        (136, 'Hoàng Mai'),
        (140, 'Nam Thăng Long'),
        (142, 'Hai Bà Trưng'),
        (144, 'Đông Anh'),
        (145, 'Bắc Thăng Long'),
        (146, 'Tây Hà Nội'),
        (188, 'Hà Thành'),
        (189, 'Tràng An'),
        (322, 'Đô Thành'),
        (324, 'Quang Trung'),
        (326, 'Thăng Long'),
        (382, 'Bắc Nam Định'),
        (424, 'Bắc Thanh Hóa'),
        (430, 'Hà Tĩnh'),
        (420, 'Thanh Hóa'),
        (444, 'Bắc Nghệ An'),
        (422, 'Sầm Sơn'),
        (380, 'Nam Định'),
        (360, 'Thái Bình'),
        (450, 'Quảng Trị'),
        (440, 'Nghệ An'),
        (441, 'Cửa Lò'),
        (400, 'Ninh Bình'),
        (402, 'Tam Điệp'),
        (470, 'Quảng Bình'),
        (384, 'Hà Nam'),
        (442, 'Vinh'),
        (520, 'Quảng Ngãi'),
        (622, 'Bảo Lộc'),
        (542, 'KCN Phú Tài'),
        (510, 'Kon Tum'),
        (502, 'Đắk Lắk'),
        (600, 'Bình Thuận'),
        (560, 'Phú Yên'),
        (482, 'Quảng Nam'),
        (506, 'Đắk Nông'),
        (462, 'Nam Thừa Thiên Huế'),
        (620, 'Lâm Đồng'),
        (610, 'Ninh Thuận'),
        (460, 'Thừa Thiên Huế'),
        (500, 'Gia Lai'),
        (540, 'Bình Định'),
        (484, 'Hội An'),
        (580, 'Khánh Hòa'),
        (488, 'Bắc Đà Nẵng'),
        (480, 'Đà Nẵng'),
        (486, 'Ngũ Hành Sơn'),
        (490, 'Sông Hàn'),
        (821, 'Hậu Giang'),
        (760, 'Tiền Giang'),
        (840, 'Kiên Giang'),
        (700, 'Long An'),
        (740, 'An Giang'),
        (704, 'Bến Lức'),
        (822, 'Sóc Trăng'),
        (724, 'Sa Đéc'),
        (980, 'Trà Vinh'),
        (742, 'Châu Đốc'),
        (780, 'Bến Tre'),
        (762, 'Tây Tiền Giang'),
        (720, 'Đồng Tháp'),
        (860, 'Cà Mau'),
        (800, 'Vĩnh Long'),
        (862, 'Bạc Liêu'),
        (820, 'Cần Thơ'),
        (824, 'Tây Cần Thơ'),
        (842, 'Phú Quốc'),
        (681, 'Nhơn Trạch'),
        (504, 'Bình Phước'),
        (662, 'Hoà Thành'),
        (680, 'Đồng Nai'),
        (682, 'KCN Biên Hòa'),
        (901, 'KCN Bình Dương'),
        (664, 'KCN Trảng Bàng'),
        (660, 'Tây Ninh'),
        (880, 'Bà Rịa-V.Tàu'),
        (640, 'Bình Dương'),
        (924, 'Chi nhánh 7'),
        (906, 'Chi nhánh 3'),
        (926, 'Chi nhánh 8'),
        (923, 'Tây Sài Gòn'),
        (900, 'CN TPHCM'),
        (902, 'Chi nhánh 1'),
        (942, 'Chi nhánh 11'),
        (928, 'Chi nhánh 9'),
        (904, 'Chi nhánh 2'),
        (945, 'Tân Bình'),
        (910, 'Nam Sài Gòn'),
        (912, 'Sài Gòn'),
        (903, 'Thủ Thiêm'),
        (920, 'Chi nhánh 5'),
        (940, 'Chi nhánh 10'),
        (944, 'Chi nhánh 12'),
        (922, 'Chi nhánh 6'),
        (947, 'Thủ Đức'),
        (930, 'Gia Định'),
        (932, 'Chợ Lớn'),
        (908, 'Chi nhánh 4'),
        (946, 'Đông Sài Gòn'),
        (948, 'Bắc Sài Gòn')
    ]

    # Chèn dữ liệu cố định vào bảng
    cursor.executemany('INSERT OR IGNORE INTO branch_users (branch_code, branch_name) VALUES (?, ?)', branch_users)

    # Lưu thay đổi và đóng kết nối
    conn.commit()
    conn.close()

# Gọi hàm để tạo bảng và thêm dữ liệu
setup_branch_users_table()

